version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/:/var/lib/mysql/
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: apioak
      MYSQL_DATABASE: apioak
      MYSQL_USER: apioak
      MYSQL_PASSWORD: apioak
    networks:
      - apioak
  apioak:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mysql
    ports:
      - "10080:10080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: apioak      
      DB_USER: apioak
      DB_PASSWORD: apioak
      TIME_ZONE: Asia/Shanghai
    networks:
      - apioak

networks:
  apioak: